services:
  process-scope:
    build: .
    image: process-scope:latest
    pid: "host"
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /proc:/host/proc:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
